/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Data Transfer Object for BeerOrderLine entities
 */
export type BeerOrderLineDto = {
    /**
     * Unique identifier for the beer order line. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the beer order line was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the beer order line was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Identifier of the beer in this order line.
     */
    beerId?: number;
    /**
     * Name of the beer in this order line.
     */
    beerName?: string;
    /**
     * Style of the beer (e.g., ALE, PALE_ALE, IPA, etc.).
     */
    beerStyle?: string;
    /**
     * Universal Product Code of the beer.
     */
    upc?: string;
    /**
     * Quantity of beer ordered.
     */
    orderQuantity: number;
    /**
     * Quantity of beer allocated from inventory.
     */
    quantityAllocated?: number;
    /**
     * Status of the beer order line.
     */
    status?: string;
};

