/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Data Transfer Object for Beer entities
 */
export type BeerDto = {
    /**
     * Unique identifier for the beer. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the beer was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the beer was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Name of the beer.
     */
    beerName: string;
    /**
     * Style of the beer (e.g., ALE, PALE_ALE, IPA, etc.).
     */
    beerStyle: string;
    /**
     * Universal Product Code, a 13-digit number assigned to each unique beer product by the Federal Bar Association.
     */
    upc: string;
    /**
     * Current quantity of beer available in stock.
     */
    quantityOnHand: number;
    /**
     * Description of the beer.
     */
    description?: string;
    /**
     * Price of the beer.
     */
    price: number;
};

